import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const outputDir = path.join(__dirname, 'output')
const reviewPath = path.join(outputDir, 'coords.review.json')
const patchJsonPath = path.join(outputDir, 'coords.selected.json')
const snippetPath = path.join(outputDir, 'routes-coordinate-snippet.ts')

async function main() {
  const review = JSON.parse(await readFile(reviewPath, 'utf8'))
  const selected = []
  const unresolved = []

  for (const item of review.items) {
    const candidate = getSelectedCandidate(item)

    if (!candidate) {
      unresolved.push({
        routeId: item.routeId,
        routeName: item.routeName,
        stopId: item.stopId,
        stopName: item.stopName,
        query: item.query,
        status: item.status,
      })
      continue
    }

    selected.push({
      routeId: item.routeId,
      routeName: item.routeName,
      stopId: item.stopId,
      stopName: item.stopName,
      dong: item.dong,
      lat: candidate.lat,
      lng: candidate.lng,
      kakaoPlaceId: candidate.kakaoPlaceId,
      kakaoPlaceName: candidate.placeName,
      address: candidate.roadAddressName || candidate.addressName,
      reviewedQuery: item.query,
    })
  }

  await mkdir(outputDir, { recursive: true })
  await writeFile(
    patchJsonPath,
    `${JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        selectedCount: selected.length,
        unresolvedCount: unresolved.length,
        selected,
        unresolved,
      },
      null,
      2,
    )}\n`,
  )

  await writeFile(snippetPath, renderSnippet(selected, unresolved))

  console.log(`Selected: ${selected.length}`)
  console.log(`Unresolved: ${unresolved.length}`)
  console.log(`Wrote ${path.relative(process.cwd(), patchJsonPath)}`)
  console.log(`Wrote ${path.relative(process.cwd(), snippetPath)}`)
}

function getSelectedCandidate(item) {
  if (item.selectedPlaceId) {
    return item.candidates.find((candidate) => candidate.kakaoPlaceId === item.selectedPlaceId)
  }

  if (Number.isInteger(item.selectedCandidateIndex)) {
    return item.candidates[item.selectedCandidateIndex]
  }

  return null
}

function renderSnippet(selected, unresolved) {
  const lines = selected
    .sort((a, b) => a.routeId - b.routeId || a.stopId.localeCompare(b.stopId))
    .map(
      (item) =>
        `  '${item.stopId}': { lat: ${item.lat}, lng: ${item.lng} }, // ${item.routeName} ${item.stopName} · ${item.kakaoPlaceName}`,
    )

  const unresolvedLines = unresolved.map(
    (item) => `// unresolved: ${item.routeName} ${item.stopName} (${item.stopId}) · ${item.query}`,
  )

  return `${[
    '// Generated by scripts/kakao-coordinate-collector/snippet.mjs',
    '// Review every coordinate before copying it into src/data/routes.ts.',
    ...unresolvedLines,
    'export const collectedCoordinates = {',
    ...lines,
    '} as const',
    '',
  ].join('\n')}`
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exitCode = 1
})
