import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { routes } from '../../src/data/routes.ts'

// 노선별 실제 도로 경로를 카카오모빌리티 길찾기(여러 경유지)로 1회 수집해
// src/data/routePaths.ts 에 정적 저장한다. REST 키는 로컬 전용(번들/커밋 금지).
const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT_PATH = path.join(__dirname, '../../src/data/routePaths.ts')
const ENDPOINT = 'https://apis-navi.kakaomobility.com/v1/waypoints/directions'

async function fetchRoadPath(restKey, route) {
  const stops = route.stops.filter((stop) => stop.lat !== undefined && stop.lng !== undefined)
  if (stops.length < 2) return null

  const origin = { x: stops[0].lng, y: stops[0].lat }
  const destination = { x: stops.at(-1).lng, y: stops.at(-1).lat }
  const waypoints = stops.slice(1, -1).map((stop) => ({ x: stop.lng, y: stop.lat }))

  const response = await fetch(ENDPOINT, {
    method: 'POST',
    headers: { Authorization: `KakaoAK ${restKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ origin, destination, waypoints, priority: 'RECOMMEND' }),
  })
  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${(await response.text()).slice(0, 200)}`)
  }

  const data = await response.json()
  const result = data.routes?.[0]
  if (!result || result.result_code !== 0) {
    throw new Error(`result_code ${result?.result_code}: ${result?.result_msg}`)
  }

  const points = []
  for (const section of result.sections ?? []) {
    for (const road of section.roads ?? []) {
      const vertexes = road.vertexes ?? []
      for (let i = 0; i + 1 < vertexes.length; i += 2) {
        const lat = Number(vertexes[i + 1].toFixed(6))
        const lng = Number(vertexes[i].toFixed(6))
        const last = points.at(-1)
        if (!last || last[0] !== lat || last[1] !== lng) points.push([lat, lng])
      }
    }
  }
  return { path: points, distance: result.summary?.distance ?? null }
}

async function main() {
  const restKey = process.env.KAKAO_REST_KEY
  if (!restKey || restKey === 'YOUR_KAKAO_REST_KEY') {
    throw new Error('KAKAO_REST_KEY가 없습니다. .env.local 설정 후 node --env-file=.env.local로 실행하세요.')
  }

  const collected = {}
  for (const route of routes) {
    process.stdout.write(`${route.name} ... `)
    try {
      const result = await fetchRoadPath(restKey, route)
      if (result) {
        collected[route.id] = result.path
        process.stdout.write(`${result.path.length} pts (${result.distance}m)\n`)
      } else {
        process.stdout.write('skip (<2 stops)\n')
      }
    } catch (error) {
      process.stdout.write(`error: ${error instanceof Error ? error.message : error}\n`)
    }
    await wait(200)
  }

  const lines = Object.keys(collected)
    .sort((a, b) => Number(a) - Number(b))
    .map((id) => `  ${id}: [${collected[id].map(([lat, lng]) => `[${lat}, ${lng}]`).join(', ')}],`)

  const output = [
    '// Generated by scripts/kakao-route-path-collector/collect.mjs',
    '// 노선별 실제 도로 경로(카카오모빌리티 길찾기, 자동차 RECOMMEND). [lat, lng] 폴리라인.',
    '// 자동차 최적경로라 실제 버스 운행 경로와 다를 수 있음(도로 모양 근사).',
    'export const routePaths: Record<number, [number, number][]> = {',
    ...lines,
    '}',
    '',
  ].join('\n')

  await writeFile(OUT_PATH, output)
  console.log(`\nWrote ${path.relative(process.cwd(), OUT_PATH)} (${Object.keys(collected).length} routes)`)
}

function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exitCode = 1
})
